install.packages("devtools", dependencies = TRUE)
install.packages("reshape2", dependencies = TRUE)
install.packages("Matrix", dependencies = TRUE)
install.packages("yaml", dependencies = TRUE)
library(devtools)
install_github("satijalab/seurat")
