EXPRESSION_INPUT_NAME: expressions_entrez.tsv
PROJECT_NAME: Mass et al., Science (2016)
MIN_CELLS: '1'
MIN_GENES: '150'
MIN_EXPRS: '0'
X_LOW_CUTOFF: '0.75'
X_HIGH_CUTOFF: '8'
Y_LOW_CUTOFF: '0.75'
Y_HIGH_CUTOFF: '12'
PCA_DIMS_FOR_TSNE: '10'

